modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="moglowstonelamps" #mandatory
version="1.0.0" #mandatory
displayName="Mo' Glowstone Lamps" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="examplemod.png" #optional
credits="TheMasterGeneral" #optional
authors="TheMasterGeneral" #optional
# The description text for the mod (multi line!) (#mandatory)
description="Mo' Glowstone Lamps"
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.moglowstonelamps]] #optional
    modId="ctdcore" #mandatory
    mandatory=true #mandatory
    versionRange="[2,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.moglowstonelamps]]
    modId="moglowstone"
    mandatory=true
    versionRange="[2,)"
    ordering="NONE"
    side="BOTH"