modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/MasterGeneral156/Mo-Glowstone-Lamps/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="moglowstonelamps" #mandatory
version="1.0.0" #mandatory
displayName="Mo' Glowstone Lamps" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/MoGlowstoneLamps.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-lamps" #optional
logoFile="examplemod.png" #optional
credits="TheMasterGeneral" #optional
authors="TheMasterGeneral" #optional
# The description text for the mod (multi line!) (#mandatory)
description="Mo' Glowstone Lamps"
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.moglowstonelamps]] #optional
    modId="ctdcore" #mandatory
    mandatory=true #mandatory
    versionRange="[2,)" #mandatory
    ordering="BEFORE"
    side="BOTH"
[[dependencies.moglowstonelamps]]
    modId="moglowstone"
    mandatory=true
    versionRange="[2,)"
    ordering="BEFORE"
    side="BOTH"