modLoader="javafml"
loaderVersion="[44,)"
license="https://github.com/MasterGeneral156/Mo-Glowstone-Lamps/blob/1.19/LICENSE"
issueTrackerURL="https://github.com/MasterGeneral156/Mo-Glowstone-Lamps/issues"

[[mods]]
modId="moglowstonelamps"
version="1.3.1b"
displayName="Mo' Glowstone Lamps"
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/MoGlowstoneLamps.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-lamps"
logoFile="logo.png"
credits="TheMasterGeneral"
authors="TheMasterGeneral"
description="RGB Glowstone Lamps!!"

[[dependencies.moglowstonelamps]]
    modId="ctdcore"
    mandatory=true
    versionRange="[2.2,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.moglowstonelamps]]
    modId="moglowstone"
    mandatory=true
    versionRange="[2.3,)"
    ordering="NONE"
    side="BOTH"