modLoader="javafml"
loaderVersion="[40,)"
license="https://github.com/MasterGeneral156/Mo-Glowstone-Lamps/blob/1.18/LICENSE"
issueTrackerURL="https://github.com/MasterGeneral156/Mo-Glowstone-Lamps/issues"

[[mods]]
modId="moglowstonelamps"
version="1.1.3"
displayName="Mo' Glowstone Lamps"
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/MoGlowstoneLamps.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-lamps"
logoFile="logo.png"
credits="TheMasterGeneral"
authors="TheMasterGeneral"
description="Mo' Glowstone Lamps"

[[dependencies.moglowstonelamps]]
    modId="ctdcore"
    mandatory=true
    versionRange="[2.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moglowstonelamps]]
    modId="moglowstone"
    mandatory=true
    versionRange="[2.1,)"
    ordering="NONE"
    side="BOTH"